[workspace]
resolver = "2"
members = ["crates/transgo-core", "crates/transgo-cli", "crates/transgo-gui"]

[workspace.package]
version = "0.2.7"
edition = "2021"
license = "MIT"
repository = "https://github.com/gozhuimeng/trans-go"
rust-version = "1.75"

[workspace.dependencies]
transgo-core = { path = "crates/transgo-core" }
transgo-gui = { path = "crates/transgo-gui" }

anyhow = "1"
arboard = { version = "3", features = ["wayland-data-control"] }
async-trait = "0.1"
base64 = "0.22"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
dirs = "6"
eframe = "0.27"
fontdb = "0.24"
hex = "0.4"
hmac = "0.12"
md-5 = "0.10"
reqwest = { version = "0.12", default-features = false, features = [
    "json",
    "rustls-tls",
    "charset",
    "http2",
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha1 = "0.10"
sha2 = "0.10"
thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
toml = "0.8"
uuid = { version = "1", features = ["v4"] }

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
opt-level = 3
panic = "abort"
