[package]
name = "transgo-gui"
description = "transgo 图形界面：封装核心库服务的独立翻译窗口"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
transgo-core.workspace = true
arboard.workspace = true
eframe.workspace = true
fontdb.workspace = true
tokio.workspace = true
